# Generated by Django 6.0.5 on 2026-05-28 15:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome_completo', models.CharField(max_length=150)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('senha_hash', models.CharField(max_length=255)),
                ('curso', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'aluno',
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='TemaTcc',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('resumo', models.TextField()),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Rejeitado', 'Rejeitado')], default='Pendente', max_length=30)),
                ('data_submissao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temas_tcc', to='gestao_tcc.aluno')),
            ],
            options={
                'db_table': 'tema_tcc',
                'ordering': ['-data_submissao'],
            },
        ),
        migrations.CreateModel(
            name='VersaoTrabalho',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('arquivo_url', models.CharField(max_length=255)),
                ('versao', models.PositiveIntegerField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('tema_tcc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versoes', to='gestao_tcc.tematcc')),
            ],
            options={
                'db_table': 'versao_trabalho',
                'ordering': ['tema_tcc', '-versao'],
            },
        ),
        migrations.CreateModel(
            name='ParecerOrientador',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comentarios', models.TextField()),
                ('apto_banca', models.BooleanField(default=False)),
                ('data_parecer', models.DateTimeField(auto_now_add=True)),
                ('versao', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parecer_orientador', to='gestao_tcc.versaotrabalho')),
            ],
            options={
                'db_table': 'parecer_orientador',
                'ordering': ['-data_parecer'],
            },
        ),
        migrations.CreateModel(
            name='AgendamentoBanca',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data_hora_inicio', models.DateTimeField()),
                ('data_hora_fim', models.DateTimeField()),
                ('local_ou_link', models.CharField(max_length=255)),
                ('tema_tcc', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='agendamento_banca', to='gestao_tcc.tematcc')),
            ],
            options={
                'db_table': 'agendamento_banca',
                'ordering': ['data_hora_inicio'],
                'indexes': [models.Index(fields=['local_ou_link', 'data_hora_inicio', 'data_hora_fim'], name='agendamento_local_o_08ebf4_idx'), models.Index(fields=['data_hora_inicio'], name='agendamento_data_ho_4dc22a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('data_hora_fim__gt', models.F('data_hora_inicio'))), name='agendamento_banca_fim_apos_inicio')],
            },
        ),
        migrations.AddConstraint(
            model_name='versaotrabalho',
            constraint=models.UniqueConstraint(fields=('tema_tcc', 'versao'), name='versao_trabalho_tema_versao_unica'),
        ),
    ]
